name = "blog-ai-analyzer"
main = "src/index.ts"
compatibility_date = "2025-03-10"

[observability]
enabled = true

kv_namespaces = [
  { binding = "RATE_LIMITS", id = "afc87bc9fcb743909383808e496b3d96" }
]
# 
# [dev]
# kv_namespaces = [
#   { binding = "RATE_LIMITS", preview_id = "afc87bc9fcb743909383808e496b3d96" }
# ]

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[dev]
[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "afc87bc9fcb743909383808e496b3d96"
